// Generated by https://quicktype.io

export interface NotionResponse {
  results: Result[];
}

export interface Result {
  object: string;
  id: string;
  created_time: string;
  last_edited_time: string;
  cover: null;
  icon: null;
  parent: Parent;
  archived: boolean;
  properties: Properties;
  url: string;
}

export interface Parent {
  type: string;
  database_id: string;
}

export interface Properties {
  description: Description;
  image: Image;
  github: Github;
  url: Github;
  name: Name;
}

export interface Description {
  id: string;
  type: string;
  rich_text: RichText[];
}

export interface RichText {
  type: string;
  text: Text;
  annotations: Annotations;
  plain_text: string;
  href: null;
}

export interface Annotations {
  bold: boolean;
  italic: boolean;
  strikethrough: boolean;
  underline: boolean;
  code: boolean;
  color: string;
}

export interface Text {
  content: string;
  link: null;
}

export interface Github {
  id: string;
  type: string;
  url: string | null;
}

export interface Image {
  id: string;
  type: string;
  files: FileElement[];
}

export interface FileElement {
  name: string;
  type: string;
  file: FileFile;
}

export interface FileFile {
  url: string;
  expiry_time: string;
}

export interface Name {
  id: string;
  type: string;
  title: RichText[];
}
